config/routes.rb
Rails.application.routes.draw do
  #get 'clubs/index'
  resources :clubs
  #get 'students/index'
  resources :students
  get 'top/index'
  root 'top#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
    #アソシエーションの設定
    has_many :students

    validates :name, length: {minimum:3, maximum:15}
    
end

app/models/student.rb
class Student < ApplicationRecord
    #アソシエーションの設定
    belongs_to:club, optional:true

    validates :student_no, :name, presence: true
    validates :name, length: {minimum:3, maximum:15}
    validates :club_id, numericality: { in: 1..20 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
    @clubs = Club.all.page(params[:page]).per(3)
  end

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)
    if @club.save
      redirect_to clubs_path
    else
      render :new
    end
  end

  def destroy
    @club = Club.find(paraams[:id])
    @club.destroy
    redirect_to clubs_path
  end
  private
  def club_params
    params.require(:club).permit(:name)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all.page(params[:page]).per(5)
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      render :new
    end
  end

  private
  def student_params
    params.require(:student).permit(:student_no, :name, :club_id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/clubs/index.html.erb
<h1>部活動一覧</h1>

<table class="table table-striped table-bordrerd">
  <tr>
    <td>部活動名</td>
    <td>操作</td>
  </tr>
  <% @clubs.each do|club| %>
    <tr>
      <td><%= club.name %></td>
    </tr>
  <% end %>
</table>
<br>

  <%= paginate @clubs %>

<p style="text-align:center"><%= link_to '新規登録', new_club_path, class: "btn btn-primary" %></p>
<p style="text-align:center"><%= link_to 'トップに戻る', root_url, class: "btn btn-primary" %></p>

app/views/clubs/new.html.erb
<h1>部活動新規登録</h1>

<%= form_with(model: @club) do |f| %>
    <% if @club.errors.any? %>
        <div>
            <h2><%= @club.errors.count %> 個のエラーがあります。</h2>
            <ul>
                <% @club.errors.full_messages.each do|message|%>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div>
        <%= f.label :name, "名前" %><br>
        <%= f.text_field :name, size: 30 %>
    </div>

    <div>
        <%= f.submit "登録" %><br>
    </div>


<% end %>

<div style="text-align:center">
    <%= link_to '一覧画面へ', clubs_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>clubmanager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>生徒一覧</h1>

<table class="table table-striped table-bordrerd">
 
  <tr>
    <td>学籍番号</td>
    <td>名前</td>
    <td>部活</td>
  </tr>
  
  <% @students.each do|student| %>
    <tr>
        <td><%= student.student_no %></td>
        <td><%= student.name %></td>
        <td><%= student.club.try(:name) %></td>
    </tr>
  <% end %>

</table>
<br>

<%= paginate @students %>

<p style="text-align:center"><%= link_to '新規登録', new_student_path, class: "btn btn-primary" %></p>
<p style="text-align:center"><%= link_to 'トップに戻る', root_url, class: "btn btn-primary" %></p>

app/views/students/new.html.erb
<h1>生徒新規登録</h1>

<%= form_with( model: @student) do |f| %>
    <% if @student.errors.any? %>
        <div>
            <h2><%= @student.errors.count %> 個のエラーがあります。</h2>
            <ul>
                <% @student.errors.full_messages.each do|message|%>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div>
        <%= f.label :student_no, "学籍番号" %><br>
        <%= f.text_field :student_no, size: 30 %>
    </div>

    <div>
        <%= f.label :name, "名前" %><br>
        <%= f.text_field :name, size: 30 %>
    </div>

    
    <div>
        <br><%= f.collection_select :club_id, Club.all, :id, :name, include_blank: "選択して下さい" %>
    </div>

    <div>
        <%= f.submit "登録" %><br>
    </div>


<% end %>



<div style="text-align:center">
    <%= link_to '一覧画面へ', students_path, class: "btn btn-primary" %>
</div>

app/views/top/index.html.erb
<h1>トップ画面</h1>

<div style="text-align:center">
    <p><%= link_to "生徒一覧画面へ", students_path, class: "btn btn-primary" %></p>
    <p><%= link_to "部活動一覧画面へ", clubs_path, class: "btn btn-primary" %></p>
</div>